#! /usr/bin/env bash

declare current=()
declare previous=()

BAR_CHAR='|'
EMPTY_CHAR=' '
BAR_LENGTH=30

if [[ -n $NO_COLOR ]]; then
    COLOR1=
    COLOR2=
    COLOR3=
    DIM=
    RST=
else
    COLOR1=$'\e[31m'
    COLOR2=$'\e[35m'
    COLOR3=$'\e[36m'
    DIM=$'\e[2m'
    RST=$'\e[0m'
fi
    
# copy the data from the current array into the previous array
copy-data(){
    previous=()

    local key value
    for key in "${!current[@]}"; do
        value=${current[$key]}
	previous[$key]=$value
    done
}

read-proc() {
    local key user nice system idle iowait irq softirq steal guest guest_nice

    local busy value num
    while read -r key user nice system idle iowait \
    irq softirq steal guest guest_nice; do
        if [[ $key != cpu* ]]; then
	    continue
	elif [[ $key == 'cpu' ]]; then
	    continue
	fi
	num=${key#cpu}

        busy=$(( user + nice + system + irq + softirq + steal + guest + nice ))
	idle=$(( idle + iowait ))

	value="$busy $idle"

	current[$num]=$value
    done < /proc/stat
}

print-bar() {
    local key=$1

    local busy1 idle1 busy2 idle2

    local space=""

    if("${!current[@]}"[-1] > 9 && key < 10); then
	space = " "
    fi

    read -r busy1 idle1 <<< "${previous[$key]}"
    read -r busy2 idle2 <<< "${current[$key]}"

    local busy=$(( busy2 - busy1 ))
    local idle=$(( idle2 - idle1 ))
    local total=$(( busy + idle ))

    local usage=$(( 1000 * busy / total ))

    local int=$((usage / 10))
    local frac=$((usage % 10))
    local perc=$int.$frac

    local num_bars=$(( usage * BAR_LENGTH / 1000 ))

    local i
    local s='['
    for ((i=0; i < num_bars; i++)); do
        s+=$COLOR1$BAR_CHAR$RST
    done
    for ((i = num_bars; i < BAR_LENGTH; i++)); do
        s+=$EMPTY_CHAR
    done
    s+=']'

    echo "$s ${COLOR2}${space}cpu$key$RST $COLOR3$perc%$RST"
}

visualise-data() {
    echo "${DIM}CPU Usage on $COLOR3$HOSTNAME${RST}"
    local key
    for key in "${!current[@]}"; do
        print-bar "$key"
    done
    local now
    printf -v now '%(%Y-%m-%d %H:%M:%S)T\n'
    echo "${DIM}$now$RST"
}

cleanup() {
    printf '\e[?1049l' # disable alternate buffer
    printf '\e[?25h' # show the cursor
}

update-window-size() {
    if [[ -n $COLUMNS ]]; then

	local cpus=( "${!CURRENT[@]}" )
	local highest_cpu=${cpus[-1]}
	
	#    []  ' ' "cpu"  len cpu num " 100.0%"
	i=$(( 2 + 1 + 3 + ${#highest_cpu} + 9 ))
        BAR_LENGTH=$((COLUMNS - i))
    fi
}

main() {
    shopt -s checkwinsize
    
    

    trap cleanup EXIT
    trap update-window-size WINCH

    printf '\e[?1049h' # enable alternate buffer
    printf '\e[?25l'  # hide the cursor
    printf '\e[H' # move the cursor home

    read-proc
    echo 'waiting for data...'
    sleep 1
    
    update-window-size

    local s
    while true; do
        copy-data
        read-proc

	s=${ visualise-data; }
	printf '\e[2J'
	printf '\e[H'
	echo -n "$s"
        sleep 1
    done
}

main
